# Setup
title: Inference
tagline: "Machine Learning"
description: "Bayesian Methods for Machine Learning"
url: "https://BLyndon.github.io/bayesian_methods/"
baseurl: "/bayesian_methods"
permalink: pretty

# About/contact
author:
  name: Benjamin Heil
  url: https://github.com/BLyndon/
  email: Benjamin.Heil@mail.de

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y
